### ISSUE TITLE
Docker GPU Support?

### ISSUE THREAD

**Issue by Mannilie** [game-ci/unity-test-runner#102]
I'm trying to perform unit tests on GPU shaders and I've gone through setting up my docker (in my self-hosted runner) to use my nvidia GPU (RTX 2080) but I still keep getting errors to do with Compute Shaders in Unity not compiling through docker.

Is there some setting in the Unity Test Runner GitHub Action that could be overwriting this value?

**Comment by webbertakken** [comment]
Are you using the latest (v2 alpha) version of test runner?

Could you also indicate which unity version you're using?

**Comment by Mannilie** [comment]
```yml
  
name: Build project
on:
  pull_request: {}
  push: { branches: [Release-DLL] }
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  testAllModes:
    name: ${{ matrix.unityVersion }} ${{ matrix.testMode }} ${{ matrix.targetPlatform }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2019.4.11f1
          #- 2020.2.0f1
        targetPlatform:
          #- StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          #- StandaloneWindows # Build a Windows standalone.
          #- StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
        testMode:
          - playmode
          #- editmode
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2.1.4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-test-runner@v2.0-alpha-3
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: true
          customParameters: -force-opengl
      - uses: actions/upload-artifact@v2
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
```
