### ISSUE TITLE
Can't expand check in test results.

### ISSUE THREAD

**Issue by spaskhalov** [game-ci/unity-test-runner#103]
Just trying to update to latest version of test-runner (v2.0-alpha-3). Alls going fine, except that i can't expand check mark to look at test results. I see only summary for Test run.
![image](https://user-images.githubusercontent.com/13979910/109992420-4c719300-7d1c-11eb-8590-a18c2db96251.png)

This is part of my workflow file:
```
  testAllModes:
    name: Test code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      - id: tests
        name: Run tests in Unity
        uses: game-ci/unity-test-runner@v2.0-alpha-3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          createCheck: true
          customImage: 'serjame/unity-editor-opencv:2020.2.3f1-opencv3.4'
          unityVersion: 2020.2.3f1
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}  
```

In attachment you can find artifact, uploaded after running tests
[Test results.zip](https://github.com/game-ci/unity-test-runner/files/6084996/Test.results.zip)
Logs archive from github action run
[logs_174.zip](https://github.com/game-ci/unity-test-runner/files/6085023/logs_174.zip)
Full workflow file
[unityBuild.yml.zip](https://github.com/game-ci/unity-test-runner/files/6085029/unityBuild.yml.zip)

**Comment by davidmfinol** [comment]
Thanks for including the logs.
The logs show that the failing test (Assets/AME.Tests/TestSceneStartup.cs:32 - AME.Tests.TestSceneStartup.TestARView) was parsed by `unity-test-runner`, so I'm not sure why you're not able to expand the check to see that.

We removed the `createCheck`, as the check is now created whenever you provide the `githubToken`. I don't necessarily think that's the cause, but can you try again after removing the `createCheck` and [Enabling Debug Logging](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging)?

**Comment by spaskhalov** [comment]
[logs_175.zip](https://github.com/game-ci/unity-test-runner/files/6085323/logs_175.zip)
Ohh I forgot to remove `createCheck` flag. Already try with and without it. This is log with enabled debug logging and without `createCheck`

**Comment by davidmfinol** [comment]
My suspicion is that the annotations are failing since it is trying to extract annotations from an empty editmode-results.xml.
There should probably be some code to handle this scenario, but I think you should be able to see the results you want by adding `testMode: playmode` to your test step:
```yaml
      - id: tests
        name: Run tests in Unity
        uses: game-ci/unity-test-runner@v2.0-alpha-3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customImage: 'serjame/unity-editor-opencv:2020.2.3f1-opencv3.4'
          testMode: playmode
```
Does that work for you?
