### ISSUE TITLE
Question : Custom parameter with CodeCoverage

### ISSUE THREAD

**Issue by mousedoc** [game-ci/unity-test-runner#130]
Is it possible?

```
      # Run Unity Testrunner
      - name : Run Unity Testrunner
        uses: game-ci/unity-test-runner@v2
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          customParameters: -debugCodeOptimization -enableCodeCoverage -coverageOptions enableCyclomaticComplexity;generateHtmlReport;generateBadgeReport -coverageResultsPath ${{ matrix.projectPath }}CodeCoverage/
```
