### ISSUE TITLE
useNetworkHost should be useHostNetwork in action.yml

### ISSUE THREAD

**Issue by paulboocock** [game-ci/unity-test-runner#140]
**Bug description**

When running this action with the `useHostNetwork` flag, GitHub Actions produces a warning:

```
Warning: Unexpected input(s) 'useHostNetwork', valid inputs are ['unityVersion', 'customImage', 'projectPath', 'testMode', 'artifactsPath', 'useNetworkHost', 'customParameters', 'sshAgent', 'githubToken', 'checkName']
```

**How to reproduce**

```
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          useHostNetwork: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

- **Expected behavior**

The above example should not produce a warning
