### ISSUE TITLE
Only 65535 characters are allowed

### ISSUE THREAD

**Issue by timcassell** [game-ci/unity-test-runner#142]
Tests pass, but the github action fails due to too many character (I'm not sure what exactly is attempting to be done).

I suspect this is due to me running over 1700 tests. Is there some way for me to get the action to pass properly?

Last lines of test run:
```
Processing file playmode-results.xml...
Trying to open artifacts/playmode-results.xml
File artifacts/playmode-results.xml parsed...
Start analyzing results: playmode-results.xml
✅ playmode-results.xml - 1721/1721 - Passed in 1353.219s
=================
Analyze result:
✅ Test Results - 1721/1721 - Passed in 1353.219s
Posting results for cdd86d6db71a1e977b579f30a8c8117bf780e8da
Error: Invalid request.

Only 65535 characters are allowed; 233873 were supplied.
```

[Edit] Forgot to include my yaml:
```yml
name: Actions

on: [push, pull_request]

jobs:
  test:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2019_4_29F1_UBUNTU }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ProtoPromise_Unity
          unityVersion: 2019.4.29f1
          testMode: PlayMode

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts

```

**Comment by davidmfinol** [comment]
That's a lot of tests! 

The Unity Test Runner actions uses the test results to generate markup and display it using the GitHub Checks API.
It looks like the large number of tests you have is causing too large a request to be sent to the Checks API, and they are rejecting it.
I did find this related issue: https://github.community/t/undocumented-65535-character-limit-on-requests/117564

The easiest workaround would be to remove `githubToken: ${{ secrets.GITHUB_TOKEN }}`, so that the Checks API is not called. But then you wouldn't be able to see the test results in the UI. You could [upload the test results artifact as mentioned here in the GameCI docs](https://game.ci/docs/github/test-runner#storing-test-results), or you could try using a different action to display the results (though I expect they will have the same error): 
```yaml
      - uses: MirrorNG/nunit-reporter@v1.0.11
        if: always()
        with:
          path: ${{ steps.test.outputs.artifactsPath }}/*.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}
```

Alternatively, maybe there's a way to split the results into smaller pieces, so that multiple smaller calls could be made to the Checks API?
