### ISSUE TITLE
Got terminal prompts disabled error when using ssh on Packages.manifest.json

### ISSUE THREAD

**Issue by Haruka0640** [game-ci/unity-test-runner#157]
**Bug description**
 - I got `terminal prompts disabled` error when try to access the package on git private repository with ssh
 - I'm specifying ssh in manifest.json, but workflow is trying to make an https connection and failing?
 - I've done the same thing with `game-ci/unity-builder`, but it works fine.

**How to reproduce**
 - Declare dependencies in `Packages/manifest.json` with `git+ssh` URL
 ```
{
  "dependencies": {
    "com.my-company.my-project.package-one": "git+ssh://git@github.com/My-Project/package_one.git?path=MyProject/com.my-company.my-project.package-one#feature/ci_test",
    "com.my-company.my-project.package-two": "git+ssh://git@github.com/My-Project/package_two.git?path=MyProject/com.my-company.my-project.package-two#feature/ci_test",    
    }
}
```
 - Execute following workflow
   ※ I've stored my ssh key to path SSH_AUTH_SOCK in previous step.
 ```
    - name: Run EditMode and PlayMode Tests
        id: tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
```
 - Got terminal prompts disabled error when accessing the package
```
  Project has invalid dependencies:
    com.my-company.my-project.package-one: Error when executing git command. fatal: could not read Username for 'https://github.com': terminal prompts disabled

```

 **Expected behavior**
 - Load the package with ssh connection without error

**Additional details**
<details>
<summary> my entire workflow </summary>

 ```
jobs:
  tests:
    name: Test Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Access to private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}    
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      - name: Run EditMode and PlayMode Tests
        id: tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}

  buildIOS:
    name: Build for ${{ matrix.targetPlatform }}-${{ matrix.environment }} by Unity
    environment: 
      name: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
        environment:
          - staging
          - production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Access to private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}       
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: |
            Library
            build/${{ matrix.targetPlatform }}
          key: Library-${{ matrix.targetPlatform }}-
          restore-keys: Library-
      - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          allowDirtyBuild: true
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: MyBuildMethod
          customParameters: -environment ${{ matrix.environment }} -applicationIdentifier ${{ secrets.IOS_APP_ID }}
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.targetPlatform }}-${{ matrix.environment }}
          path: build/${{ matrix.targetPlatform }}
```
</details>

<details>

<summary> error log </summary>

```
Rebuilding Library because the asset database could not be found!
[Package Manager] Done resolving packages in 32.01s seconds
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.my-company.my-project.package-one: Error when executing git command. fatal: could not read Username for 'https://github.com': terminal prompts disabled

    You may need to set up a Git credentials helper
    to access a private repository.
    com.my-company.my-project.package-two: Error when executing git command. fatal: could not read Username for 'https://github.com': terminal prompts disabled

    You may need to set up a Git credentials helper
    to access a private repository.

A re-import of the project may be required to fix the issue or a manual modification of /github/workspace/Packages/manifest.json file.
/home/bokken/buildslave/unity/build/External/baselib/builds/Include/C/Internal/Baselib_Semaphore_FutexBased.inl.h(151): Assertion failed (count >= 0) - Destruction is not allowed when there are still threads waiting on the semaphore.
Unexpected exit code 133
```

</details>
