### ISSUE TITLE
Got Access token is unavailable Error when use githubToken option

### ISSUE THREAD

**Issue by Haruka0640** [game-ci/unity-test-runner#161]
**Description of the bug
 - When adding the githubToken option according to [documentation](https://game.ci/docs/github/test-runner#viewing-test-results), `Access token is unavailable Error` occurs.
 - If the option is removed, the Action succeeds.

**How to reproduce
 1. Create a Github personal access token with full access and no expiration date.
 1. Pass the PAT to the githubToken option of `game-ci/unity-test-runner@v2`.
 1. Action failed.

**expected behavior**.
- Action succeeded.

**Additional details**
<details>

<summary> My workflow </summary> 

```
name: Test, Build, and Release My Demo

on: 
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 19 * * 1-5'

jobs:
  tests:
    name: Test Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Access to private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}    
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      - name: Run EditMode and PlayMode Tests
        id: tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
```

</details>

<details>

<summary> Error message </summary>

```
###########################
#    Play Mode Results    #
###########################

<?xml version="1.0" encoding="utf-8"?>
<test-run id="2" testcasecount="0" result="Passed" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0" engine-version="3.5.0.0" clr-version="4.0.30319.42000" start-time="2022-01-21 09:33:34Z" end-time="2022-01-21 09:33:34Z" duration="0.0027389">
  <test-suite type="TestSuite" id="1000" name="My Demo" fullname="MOOOS Demo" runstate="Runnable" testcasecount="0" result="Passed" start-time="2022-01-21 09:33:34Z" end-time="2022-01-21 09:33:34Z" duration="0.002739" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0">
    <properties />
  </test-suite>
</test-run><test-run id="2" testcasecount="0" result="Passed" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0" engine-version="3.5.0.0" clr-version="4.0.30319.42000" start-time="2022-01-21 09:33:34Z" end-time="2022-01-21 09:33:34Z" duration="0.0027389">
Changing to "/github/workspace/_activate-license" directory.
/github/workspace/_activate-license /github/workspace
Unity Editor version:    2021.2.6f1 (8c4e826ba445)
Branch:                  2021.2/staging
Build type:              Release
Batch mode:              YES
System name:             Linux
Distro version:          #27~20.04.1-Ubuntu SMP Fri Jan 7 15:02:06 UTC 2022
Kernel version:          5.11.0-1025-azure
Architecture:            x86_64
Available memory:        6951 MB
[Licensing::Module] Channel doesn't exist: "LicenseClient-root"
[Licensing::Module] Successfully launched the LicensingClient (PId: 2362)
[SignatureVerifier] Application signature verification not supported on this platform.
[LicensingClient] Handshaking with LicensingClient (version: 1.9.0+249add7)
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root" (connect: 0.45s, validation: 0.09s, handshake: 0.00s)
[Licensing::Module] Connected to LicensingClient (PId: 2362, launch time: 0.00, total connection time: 0.54s)
Entitlement-based licensing initiated
[Licensing::Module] Error: Access token is unavailable
[Licensing::Module] Error: Failed to return entitlement license
```

</details>
