### ISSUE TITLE
Test-Runner Changes Project Settings file

### ISSUE THREAD

**Issue by Hussein-Attie** [game-ci/unity-test-runner#168]
**Bug description**

Test Runner changes 

ProjectSettings/ProjectSettings.asset
specifically it edits this setting 
runInBackground: 0
to
runInBackground: 1

this change is not reversed after the testing step is done, and so the branch is flagged "dirty" and this prevents the Building step from being executed.

  And this error is showed 

  ```
Warning: Changes were made to the following files and folders:

Warning:  M ProjectSettings/ProjectSettings.asset

Error: Branch is dirty. Refusing to base semantic version on uncommitted changes
```

**How to reproduce**

run the Test Runner step with any configuration on a unity project in a github repository through git hub action as follows:
 
```
name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
     # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

          
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64 


      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build


```
- **Expected behavior**

if the testing step runs successfully,the build should also run successfully and produce the built project as an artifact 

**Additional details**

The project is built successfully if the same script is used but with out the test runner step, so the test runner is probably creating the problem  
This is the project : https://github.com/Hussein-Attie/BugFixing3.git
