### ISSUE TITLE
WebGL: Calling JavaScript functions from Unity scripts fails

### ISSUE THREAD

**Issue by FeepsDev** [game-ci/unity-test-runner#178]
**Bug description**
When running tests for the WebGL platform, it fails when I call JavaScript imported functions:

`System.EntryPointNotFoundException : MyJSMethod assembly:<unknown assembly> type:<unknown type> member:(null) at (wrapper managed-to-native)`

**How to reproduce**

[Import a javascript function](https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html) and use it :

```cs
[DllImport("__Internal")]
internal static extern void MyJSMethod(int arg);
```

**Expected behavior**

JavaScript functions being called 

**Additional details**
I don't know if this is related, but I found this in my build logs:
`Native extension for WebGL target not found`

EDIT: Note that running my tests from the TestRunner of the Editor works well 

Thanks in advance

**Comment by timcassell** [comment]
What does your yaml look like? How are you running WebGL tests? Unity test runner doesn't support platform tests outside of the editor. See https://github.com/game-ci/unity-test-runner/issues/163#issuecomment-1040189227

**Comment by FeepsDev** [comment]
The workflow looks like this: 
```yaml
name: UnityBridge Tests
on: [push, pull_request]

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          customImage: unityci/editor:ubuntu-2021.2.18f1-webgl-1.0.0
          projectPath: TestProject~
          testMode: playmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
```

By running the tests in the editor I just mean I just click the "Run tests on WebGL" button so it starts my browser
