### ISSUE TITLE
Code Coverage Options With Combined Coverage Results

### ISSUE THREAD

**Issue by jhornsb2** [game-ci/unity-test-runner#181]
**Context**

I know it is possible to get code coverage using the custom parameters option like this:

```yaml
- name: Code Coverage
  uses: game-ci/unity-test-runner@v2
  id: tests
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    artifactsPath: code-coverage-artifacts
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    checkName: Code Coverage Test Results
    customParameters: -debugCodeOptimization -enableCodeCoverage -coverageOptions generateHtmlReport;generateBadgeReport;assemblyFilters:+<assets> -coverageResultsPath code-coverage-artifacts
```

This works great for getting the coverage results for a single editmode or playmode test run, but it is unable to get the combined coverage results from running something similar to the following script:

```bash
./Unity.exe -projectPath <project-path> -batchmode -testPlatform editmode -runTests -debugCodeOptimization -enableCodeCoverage -coverageResultsPath <results-path> -coverageOptions "generateAdditionalMetrics;assemblyFilters:+<assets>"

./Unity.exe -projectPath <project-path> -batchmode -testPlatform playmode -runTests -debugCodeOptimization -enableCodeCoverage -coverageResultsPath <results-path> -coverageOptions "generateAdditionalMetrics;assemblyFilters:+<assets>"

./Unity.exe -projectPath "C:/Users/Joshua/Documents/Code Projects/GrizzledOwl/common-ci-cd" -batchmode -debugCodeOptimization -enableCodeCoverage -coverageResultsPath <results-path> -coverageOptions "generateHtmlReport;generateBadgeReport;assemblyFilters:+<assets>" -quit
```
In a lot of cases this combined report is what a lot of people will want when looking at code coverage.

With the information from this the people/teams using this script would be able to use that metric to enforce a minimum code coverage standard on their repositories.

**Suggested solution**

In order to support the above, I would suggest adding in a "codeCoverage" option flag to the action. I would have it work as follows:
1. When the "testMode" option is "editmode" - creates the code coverage report for editmode tests.
2. When the "testMode" option is "playmode" - creates the code coverage report for playmode tests.
3. When the "testMode" option is "all" - generate combined coverage result. 

I would probably add a flag "coverageOnly" so that the test results could be skipped if they aren't needed.

Not only would this support the feature, but it would make it a little clearer to people who are trying to use this action how to get coverage results. In my opinion, it would also make their GitHub actions a little bit more readable.

I would also add an option for "coverageReportType" that would let you specify which reports you are wanting. This would have three options:
1. html - generates the html coverage report
2. badge - generates the coverage summary badges
3. both - generates both the html report and summary badges

I would have this default to the "both" option.

I would add an option for "assemblyFilters" that would let you define what assemblies to include. This would just place your options into the correct place.

To round this out, I would add "coverageOptions". This would be the direct input for the coverageOptions that will be in the batch mode call. Honestly, with this coverageReportType and assemblyFilters wouldn't be needed, but since those options are the ones that are used most often, I think it makes sense to specify them up front in order to make it easier and more readable for people using the action.

Finally, I would add a "minimumCoverage" option. It wouldn't be required, would default to 0, and the allowed values would be a number between 0 and 100. If this is provided, when the coverage results are in, the script would perform a check to see if the coverage meets or exceeds the provided value. If it does, it passes. If it doesn't, it fails.

Using these options would look something like this:
```yaml
- name: Code Coverage
  uses: game-ci/unity-test-runner@v2
  id: tests
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    artifactsPath: code-coverage-artifacts
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    checkName: Code Coverage Test Results
    testMode: all
    codeCoverage:
    coverageOnly:
    coverageReportType: both
    assemblyFilters: +<assets>
    # coverageOptions: verbosity? generateTestReferences? sourcePaths? etc...
    customParameters: -debugCodeOptimization -burst-disable-compilation
    minimumCoverage: 80
```

**Considered alternatives**

I don't really have any alternatives, outside of writing my own custom script, to handle these things.

**Additional details**

I thought about writing my own custom script to handle these things, but it seems like something others would want as well. I am already using game-ci in my other GitHub actions for my projects, so I wanted to see if this was a feature that would be desired here. 

I have seen other code coverage issues and pull requests, but I wasn't sure if they were just dropped because they only covered the basic solution that can be handled with customParameters, or if directly supporting coverage wasn't desired for this repository.

I was planning on forking the repository and implementing this myself, but I wanted to discuss my solution, and see if this was even desired.
