### ISSUE TITLE
Issues with using ssh keys (sshAgent)

### ISSUE THREAD

**Issue by sviper-marco-behnke** [game-ci/unity-test-runner#205]
Hello! I have setup my pipeline with the suggest way of integrating a ssh agent since we require a private repository
But I am running into an error when executing the runner

```
An error occurred while resolving packages:
  Project has invalid dependencies:
    de.project.fancypackage: Error when executing git command. ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
    Host key verification failed.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
```

This is how it is integrated

```
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY}}

      - uses: game-ci/unity-test-runner@v2
        id: tests
        with:
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
```

Any idea of what is going on here?

**Comment by hraytilakhealthcare** [comment]
Exact same issue here, took me two days to pinpoint the reason to this. Let me know if you found anything @sviper-marco-behnke .

I'll update the issue with my own findings if applicable.

**Comment by hraytilakhealthcare** [comment]
Alrighty, the issue was between the keyboard and the chair, I added the `sshAgent` to then `env:` paragraph instead of `with:` by accident. Package resolving seem to work as expected now.

The working paragraph looks like this:

```yaml
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.INTERNAL_PACKAGE_CLONE_KEY }}

      - name: Running Unity Test Runner
        uses: game-ci/unity-test-runner@v2.1.1
        id: testRunner
        with:
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
          testMode:
            editmode
            githubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

```

Good luck !
