### ISSUE TITLE
Error: Only 65535 characters are allowed

### ISSUE THREAD

**Issue by MrGadget1024** [game-ci/unity-test-runner#214]
Still getting this error, not fixed by https://github.com/game-ci/unity-test-runner/commit/b9980d6db77b429efa66b950aef387eea018775d

```yml
- name: Run editor Tests
  continue-on-error: true
  uses: game-ci/unity-test-runner@main
```

```
Processing file editmode-results.xml...
Trying to open artifacts/editmode-results.xml
File artifacts/editmode-results.xml parsed...
Start analyzing results: editmode-results.xml
⚠️ editmode-results.xml - 991/1003, skipped: 12 - Passed in 107.210s
=================
Analyze result:
⚠️ Test Results - 991/1003, skipped: 12 - Passed in 107.210s
Posting results for 953944bREDACTEDf5fc69cf8e7c906d266cef5ef
Error: Invalid request.

Only 65535 characters are allowed; 75929 were supplied.
```
