### ISSUE TITLE
Inconsistent licence activation

### ISSUE THREAD

**Issue by ironcutter24** [game-ci/unity-test-runner#245]
**Bug description**

I get an **`Unclassified error occured while trying to activate license`** error, even though I can get a successful cloud build with the same licence and credentials.

**How to reproduce**

Set `UNITY_LICENSE`, `UNITY_EMAIL`, `UNITY_PASSWORD` secrets.
`UNITY_VERSION` = "2022.3.5f1"
`BUILD_TARGET_PLATFORM` = "StandaloneWindows64"

Run main.yml workflow on a Unity 2022.3.5f1 project.

main.yml
```yaml
name: Actions 😎

on: [push, pull_request]

jobs:
  test:
    name: Test my project 🧪
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: ${{ secrets.UNITY_VERSION }}

  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ secrets.BUILD_TARGET_PLATFORM }}
          unityVersion: ${{ secrets.UNITY_VERSION }}
          allowDirtyBuild: true

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

```
**Expected behavior**

Licence should be activated and tests should continue.

**Additional details**

![image](https://github.com/game-ci/unity-test-runner/assets/33135141/b957cb3b-6d31-43c1-b569-06921a748c47)

End of test log:
```
...
Status: Downloaded newer image for unityci/editor:ubuntu-2022.3.5f1-linux-il2cpp-3
Changing to "/github/workspace/_activate-license" directory.
/github/workspace/_activate-license /github/workspace
Requesting activation (personal license)
Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1
```
