### ISSUE TITLE
Reasource not Available by Integration

### ISSUE THREAD

**Issue by derjacklive** [game-ci/unity-test-runner#249]
**Bug description**
Hello People of Game-CI
i would like some help:
i keep geting a error:
Resource not Available by Integration
Log at the bottom

Thank you in front

**How to reproduce**

1. Copy my Ci.yaml
2. Test a Project
3. Get a Error

**Expected behavior**

Testing The Project

**Additional details**

My CI.yaml:
```
name: Automatic CI 🤖

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

on:
  pull_request:
  workflow_dispatch:

jobs:
  testRunner:
    name: Test in ${{ matrix.testMode }} ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:
      - name: Checkout code ✅
        uses: actions/checkout@v4

      - name: Create LFS file list 📜
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache 🔄
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull 📥
        run: |
          git lfs pull
          git add .
          git reset --hard
      - name: Restore Library cache 🔄
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-test-project-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-test-project-
            Library-
            
      - name: Run ${{ matrix.testMode }} Tests ⏯ 📑
        id: runningTest
        uses: game-ci/unity-test-runner@v3.1.0
        with:
          projectPath: ${{ vars.projectPath }}
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} test results
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts
      - name: Upload Artifact 📦
        uses: actions/upload-artifact@v3
        with:
          name: Test results (${{ matrix.testMode }}) 📑
          path: ${{ steps.runningTest.outputs.artifactsPath }}
```

Log:
[Pastebin](https://pastebin.com/QU9H0FZT)

**Comment by GabLeRoux** [comment]
Closing this as I'm quite sure the answer solves the issue. I've encountered this a few times and this was the solution.

**Comment by shloon** [comment]
Hi, a better fix is to explicitly add the required permissions to the job using this action, e.g.:
```yaml
jobs:
  test:
    permissions:
      checks: write
...
    steps:
      - name: Run Tests
        uses: game-ci/unity-test-runner@v4
```

You can see that in action in my own repo here: https://github.com/shloon/Event-Horizon/blob/b13d2c16be65e5ce1b6fc0e0fd3bbf4bab9ec434/.github/workflows/ci.yml#L8
