### ISSUE TITLE
Linecoverage: No such file or directory

### ISSUE THREAD

**Issue by FrancoisGo** [game-ci/unity-test-runner#250]
**Bug description**

When running editmode tests on circle ci I got this error : `grep: Linecoverage: No such file or directory`
When looking in the circle ci orb I saw this [line 718](https://circleci.com/developer/orbs/orb/game-ci/unity#quick-start) : `grep "$unity_project_full_path"/"$PARAM_TEST_PLATFORM"-coverage/Report/Summary.xml Linecoverage`
But if I'm right the grep command doesn't work like this it should be `grep "string" path`

**How to reproduce**

Run test on circle ci in editmode.
Here is my circle ci job :
```
  test:
    executor:
      name: 'unity/ubuntu'
      target_platform: 'android'
      editor_version: '2022.3.11f1'
      resource_class: 'large'
    steps:
      - custom_checkout
      - unity/prepare-env:
          project-path: '******'
      - unity/test:
          project-path: '******'
          test-platform: 'editmode'
          custom-parameters: '-buildTarget "Android" -disable-assembly-updater -coverageOptions "useProjectSettings"'
```
