### ISSUE TITLE
corrupted size vs. prev_size error

### ISSUE THREAD

**Issue by Drummerboy444** [game-ci/unity-test-runner#59]
Hi,

I'm running into an intermittent issue while using the test runner on my project. Around half of the time the tests will run and pass successfully, but sometimes I'll get the following message in the logs of the job:
```
###########################
#   Testing in PlayMode   #
###########################

[0618/122644:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[0618/122647:ERROR:sandbox_linux.cc(308)] InitializeSandbox() called with multiple threads in process gpu-process
corrupted size vs. prev_size
```
Once this happens, the action just seems to hang and will never complete (until I manually stop it or it hits the timeout).

Unity version: 2019.2.0f1
unity-test-runner version: 1.6

I'm not really sure what other information to provide, but let me know if there's any other information that would be useful and I'll provide it.

EDIT: Adding my workflow file as I think it might be useful to see:

```yml
name: Test

on:
  pull_request:
    branches:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Run Unity tests for ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        projectPath:
          - Danki2
        unityVersion:
          - 2019.2.0f1
        testMode:
          - playmode

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-

      - name: Test
        uses: webbertakken/unity-test-runner@v1.6
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}

```
