### ISSUE TITLE
Is it possible to use non base editor image?

### ISSUE THREAD

**Issue by lvgrecords** [game-ci/unity-test-runner#89]
I'm trying to use `2020.1.17f1-ios-0` but getting an error below:

```
Run webbertakken/unity-test-runner@v2.0-alpha-1
/usr/bin/docker build /home/lvg/actions-runner/_work/_actions/webbertakken/unity-test-runner/v2.0-alpha-1/action --file /home/lvg/actions-runner/_work/_actions/webbertakken/unity-test-runner/v2.0-alpha-1/action/Dockerfile --build-arg IMAGE=unityci/editor:2020.1.17f1-ios-0-base-0 --tag unity-action:2020.1.17f1-ios-0-base-0
Sending build context to Docker daemon  144.4kB

Step 1/14 : ARG IMAGE
Step 2/14 : FROM $IMAGE
manifest for unityci/editor:2020.1.17f1-ios-0-base-0 not found: manifest unknown: manifest unknown
Error: The process '/usr/bin/docker' failed with exit code 1
```

My workflow:
```yaml
name: Continuous Integration

on:
  pull_request: { }
  push: { branches: [ master ] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2020.1.17f1-ios-0

jobs:
  unit-tests:
    name: Unit Tests
    #    runs-on: ubuntu-20.04
    runs-on: self-hosted
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.3
        with:
          path: Library
          key: Library
      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v2.0-alpha-1
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
```

Looks `-base-0` is added on runtime. Are there ability to use editor+modules based docker images eg `2020.1.17f1-ios-0`?
Unfortunately using it's a required workaround for googlesamples/unity-jar-resolver#412

In case it's not supported at that moment I do not mind to add such support myself by PR
